
# Task Analysis {.appendix}

Here are some questions to guide you through the process of doing a task analysis. You don't have to specifically answer each one of these (and some may not apply), but they should get you started thinking in the right direction. 

-------------------------------------------------------

What are the prerequisites, for both knowledge and e.g. software setup?

Some prequisites would have some sort of understanding of the structure of their data and understand who their audience is.

For software setup it would be important to have r as well as rstudio installed.

-------------------------------------------------------

What are the basic requirements for any data that the method is used on? 
  - Are missing values allowed? It would depend on if the missing values would negatively impact the overall reliability of the data
  - Should the data be confined within a certain range? The user topic is on communicating and analyzing risk so the range would not be confined.
  - Does the data have to be approximately normally distributed? The data would not need to be normally distributed because the distribution does not impact whether or not you can calculate risk.

------------------------------------------------------

What are the basic components of the task?
  - Outline these in a bit more detail
  
  Downloading related packages (riskyr and ggdibbler), as well as reading in the given dataset (synthetic). 
  
  Apply the given riskyr functions to find the given risk (Generates the risk of getting a disease from a given action)
  
  Apply the 5 levels of precision mentioned in the annual review article (Numbers given to appropriate levels of prevision, A distribution or range, A measure of stiatistical significance compared with a null hypothesis, verbal qualifers to numbers, and refusal to give a number unless the evidence is good enough. 
  
  Apply the given ggdibbler functions to construct a graphic to give a visual refrence to enhance the effects of the 5 levels of precision

-------------------------------------------------------

What decisions does the user need to be prepared to make on the fly? 

The user will need to be prepared to identify how to apply the 5 levels of precision and decide where it is necessary to implement that into their own design. 

The user will need to have to be able to install the given packages's dependencies. 

The user will need to decide how they would like to implement their graphics into ggdibbler

-------------------------------------------------------

What questions should the user ask of the "first draft" of the product? What adjustments may need to be made?

Using more adaptable data

Going further into the 5 levels of precision

Using more examples in ggdibbler to help with variety

## Additional Guidance 

Your check-in should answer these basic questions (and similar concerns that apply more directly to your topic). 

Once you've completed the check-in, you can use this section to jump-start an introduction/set-up/getting started section in your user guide. 
This document should remain as an appendix to your main report. 